### ISSUE TITLE
2.8 error assigning one value to 2 variables

### ISSUE THREAD

**Issue by alexparry** [raspberrypilearning/fl-programming-robotics#2]
Some learners are getting the following error when using the code
`pulse_start, pulse_end = 0`

and reporting a fix by using 
`pulse_start, pulse_end = 0, 0`

Traceback (most recent call last):
File "/home/pi/Desktop/uds-detect-objects.py", line 30, in <module>
duration = get_pulse_time()
File "/home/pi/Desktop/uds-detect-objects.py", line 10, in get_pulse_time
pulse_start, pulse_end = 0
TypeError: cannot unpack non-iterable int object

**Comment by alexparry** [comment]
Updated the code and step
